@extends('layouts.app')

@section('content')
    <!-- Animated Background Particles -->
    <div class="particles">
        <!-- Particles will be generated by JavaScript -->
    </div>

    <div class="container mt-5">
        <!-- Header Section -->
        <div class="header-section fade-in">
            <h1 class="main-title">My Polls</h1>
            <p class="lead text-white text-center mb-4" style="font-size: 1.2rem; text-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);">
                Discover and participate in polls from your polls created
            </p>

            <!-- Loading Indicator -->
            <div class="loading-spinner text-center mb-4" id="loadingSpinner">
                <div class="glass-card" style="display: inline-block; padding: 2rem 3rem;">
                    <div class="spinner-border text-white mb-3" role="status" style="width: 3rem; height: 3rem;">
                        <span class="visually-hidden">Loading...</span>
                    </div>
                    <p class="text-white mb-0 fw-bold">Loading amazing polls...</p>
                </div>
            </div>
        </div>

        <!-- Polls Container -->
        <div class="row" id="pollListByUser">
            <!-- Polls will be loaded here -->
        </div>

        <!-- Back to Categories Button -->
        <div class="text-center mt-5 fade-in">
            <a href="{{ route('dashboard') }}" class="btn-glass btn-primary-glass">
                <i class="fas fa-arrow-left"></i>
                Back to Dashboard
            </a>
        </div>
    </div>

    <!-- Enhanced Styles with Dashboard Theme -->
    <style>
        :root {
            --primary-gradient: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            --poll-gradient: linear-gradient(135deg, #ff6b6b 0%, #4ecdc4 50%, #45b7d1 100%);
            --success-gradient: linear-gradient(135deg, #56ab2f 0%, #a8e6cf 100%);
            --danger-gradient: linear-gradient(135deg, #ff416c 0%, #ff4b2b 100%);
            --info-gradient: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            --glass-bg: rgba(255, 255, 255, 0.15);
            --glass-border: rgba(255, 255, 255, 0.25);
            --text-primary: #2c3e50;
            --text-secondary: #7f8c8d;
            --card-shadow: 0 8px 32px rgba(31, 38, 135, 0.37);
        }

        body {
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 25%, #ff6b6b 50%, #4ecdc4 75%, #45b7d1 100%);
            background-size: 400% 400%;
            animation: gradientFlow 15s ease infinite;
            min-height: 100vh;
            position: relative;
            overflow-x: hidden;
        }

        @keyframes gradientFlow {
            0% {
                background-position: 0% 50%;
            }

            50% {
                background-position: 100% 50%;
            }

            100% {
                background-position: 0% 50%;
            }
        }

        /* Animated Background Particles */
        .particles {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            pointer-events: none;
            z-index: 1;
        }

        .particle {
            position: absolute;
            background: rgba(255, 255, 255, 0.1);
            border-radius: 50%;
            animation: float 8s ease-in-out infinite;
        }

        .particle:nth-child(odd) {
            animation-direction: reverse;
            background: rgba(255, 107, 107, 0.1);
        }

        .particle:nth-child(3n) {
            background: rgba(78, 205, 196, 0.1);
        }

        @keyframes float {

            0%,
            100% {
                transform: translateY(0px) rotate(0deg);
            }

            33% {
                transform: translateY(-40px) rotate(120deg);
            }

            66% {
                transform: translateY(-80px) rotate(240deg);
            }
        }

        /* Container styling */
        .container {
            position: relative;
            z-index: 2;
        }

        /* Glass morphism effects */
        .glass-card {
            background: var(--glass-bg);
            backdrop-filter: blur(20px);
            border: 1px solid var(--glass-border);
            border-radius: 20px;
            box-shadow: var(--card-shadow);
            transition: all 0.4s cubic-bezier(0.4, 0, 0.2, 1);
        }

        .glass-card:hover {
            transform: translateY(-8px);
            box-shadow: 0 12px 40px rgba(31, 38, 135, 0.5);
            border-color: rgba(255, 255, 255, 0.4);
        }

        /* Header section */
        .header-section {
            text-align: center;
            padding: 2rem 0;
            margin-bottom: 2rem;
        }

        .main-title {
            font-size: 3.5rem;
            font-weight: 900;
            background: linear-gradient(135deg, #ffffff 0%, #f8f9ff 50%, #e3f2fd 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
            text-shadow: 0 0 30px rgba(255, 255, 255, 0.5);
            animation: titleGlow 3s ease-in-out infinite alternate;
            margin-bottom: 1rem;
        }

        @keyframes titleGlow {
            from {
                text-shadow: 0 0 20px rgba(255, 255, 255, 0.5);
                transform: scale(1);
            }

            to {
                text-shadow: 0 0 40px rgba(255, 255, 255, 0.8), 0 0 60px rgba(255, 255, 255, 0.4);
                transform: scale(1.02);
            }
        }

        /* Button styles */
        .btn-glass {
            background: var(--glass-bg);
            backdrop-filter: blur(10px);
            border: 1px solid var(--glass-border);
            color: white;
            padding: 12px 30px;
            border-radius: 50px;
            font-weight: 600;
            transition: all 0.3s ease;
            position: relative;
            overflow: hidden;
            text-decoration: none;
            display: inline-flex;
            align-items: center;
            gap: 8px;
        }

        .btn-glass::before {
            content: '';
            position: absolute;
            top: 0;
            left: -100%;
            width: 100%;
            height: 100%;
            background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.3), transparent);
            transition: left 0.6s;
        }

        .btn-glass:hover::before {
            left: 100%;
        }

        .btn-glass:hover {
            transform: translateY(-3px);
            box-shadow: 0 15px 35px rgba(0, 0, 0, 0.3);
            color: white;
        }

        .btn-primary-glass {
            background: var(--poll-gradient);
            border: none;
        }

        /* Modern Poll Cards with Glass Effect */
        .modern-poll-card {
            background: var(--glass-bg);
            backdrop-filter: blur(20px);
            border: 1px solid var(--glass-border);
            border-radius: 20px;
            box-shadow: var(--card-shadow);
            transition: all 0.4s cubic-bezier(0.4, 0, 0.2, 1);
            overflow: hidden;
            position: relative;
            cursor: pointer;
            animation: fadeInUp 0.6s cubic-bezier(0.4, 0, 0.2, 1);
            /* margin-bottom: 1.5rem; */
        }

        .modern-poll-card::after {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            height: 4px;
            background: var(--poll-gradient);
            border-radius: 20px 20px 0 0;
        }

        .modern-poll-card:hover {
            transform: translateY(-8px);
            box-shadow: 0 12px 40px rgba(31, 38, 135, 0.5);
            border-color: rgba(255, 255, 255, 0.4);
        }

        .modern-poll-card .card-body {
            padding: 2rem;
            position: relative;
            z-index: 2;
        }

        .modern-poll-card .poll-question {
            color: white;
            font-weight: 700;
            font-size: 1.4rem;
            line-height: 1.4;
            margin-bottom: 0.8rem;
            text-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
            display: -webkit-box;
            -webkit-line-clamp: 2;
            -webkit-box-orient: vertical;
            overflow: hidden;
        }

        .modern-poll-card .category-badge {
            display: inline-block;
            padding: 0.6rem 1.2rem;
            background: var(--poll-gradient);
            color: white;
            border-radius: 50px;
            font-size: 0.9rem;
            font-weight: 600;
            margin-bottom: 1rem;
            box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);
        }

        .modern-poll-card .poll-meta {
            color: rgba(255, 255, 255, 0.9);
            font-size: 0.9rem;
            margin-bottom: 1.5rem;
            display: flex;
            align-items: center;
            line-height: 1.6;
        }

        .modern-poll-card .poll-meta i {
            margin-right: 0.5rem;
            color: rgba(255, 255, 255, 0.7);
        }

        .modern-poll-card .view-btn {
            background: var(--poll-gradient);
            border: none;
            color: white;
            padding: 0.75rem 2rem;
            border-radius: 50px;
            font-weight: 600;
            text-decoration: none;
            display: inline-flex;
            align-items: center;
            gap: 8px;
            transition: all 0.3s ease;
            box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);
            position: relative;
            overflow: hidden;
        }

        .modern-poll-card .view-btn::before {
            content: '';
            position: absolute;
            top: 0;
            left: -100%;
            width: 100%;
            height: 100%;
            background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.3), transparent);
            transition: left 0.6s;
        }

        .modern-poll-card .view-btn:hover::before {
            left: 100%;
        }

        .modern-poll-card .view-btn:hover {
            transform: translateY(-2px);
            box-shadow: 0 8px 25px rgba(0, 0, 0, 0.3);
            color: white;
        }

        .modern-poll-card .view-btn i {
            transition: transform 0.3s ease;
        }

        .modern-poll-card:hover .view-btn i {
            transform: translateX(3px);
        }

        /* Empty State */
        .empty-state {
            background: var(--glass-bg);
            backdrop-filter: blur(20px);
            border: 1px solid var(--glass-border);
            border-radius: 20px;
            box-shadow: var(--card-shadow);
            padding: 4rem 2rem;
            text-align: center;
            animation: fadeInUp 0.8s cubic-bezier(0.4, 0, 0.2, 1);
        }

        .empty-state i {
            font-size: 4rem;
            color: rgba(255, 255, 255, 0.7);
            margin-bottom: 1.5rem;
        }

        .empty-state h3 {
            color: white;
            font-weight: 700;
            margin-bottom: 1rem;
            text-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
        }

        .empty-state p {
            color: rgba(255, 255, 255, 0.9);
            font-size: 1.1rem;
            line-height: 1.6;
        }

        /* Error State */
        .error-state {
            background: var(--glass-bg);
            backdrop-filter: blur(20px);
            border: 1px solid var(--glass-border);
            border-radius: 20px;
            box-shadow: var(--card-shadow);
            padding: 3rem 2rem;
            text-align: center;
            animation: fadeInUp 0.8s cubic-bezier(0.4, 0, 0.2, 1);
        }

        .error-state i {
            font-size: 3rem;
            color: #ff6b6b;
            margin-bottom: 1rem;
        }

        .error-state h3 {
            color: white;
            font-weight: 700;
            margin-bottom: 0.5rem;
            text-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
        }

        .error-state p {
            color: rgba(255, 255, 255, 0.9);
            margin-bottom: 1.5rem;
        }

        /* Loading animations */
        .fade-in {
            animation: fadeInUp 0.8s ease-out forwards;
            opacity: 0;
        }

        .fade-in:nth-child(1) {
            animation-delay: 0.1s;
        }

        .fade-in:nth-child(2) {
            animation-delay: 0.2s;
        }

        .fade-in:nth-child(3) {
            animation-delay: 0.3s;
        }

        .fade-in:nth-child(4) {
            animation-delay: 0.4s;
        }

        @keyframes fadeInUp {
            from {
                opacity: 0;
                transform: translateY(50px);
            }

            to {
                opacity: 1;
                transform: translateY(0);
            }
        }

        /* Responsive Design */
        @media (max-width: 768px) {
            .main-title {
                font-size: 2.5rem;
            }

            .modern-poll-card .card-body {
                padding: 1.5rem;
            }

            .modern-poll-card .poll-question {
                font-size: 1.2rem;
            }

            .empty-state {
                padding: 3rem 1.5rem;
            }
        }
    </style>
@endsection

@push('scripts')
    <script>
        $(document).ready(function() {
            // Generate animated particles
            function createParticles() {
                const particlesContainer = document.querySelector('.particles');
                const particleCount = 50;

                for (let i = 0; i < particleCount; i++) {
                    const particle = document.createElement('div');
                    particle.className = 'particle';

                    // Random size between 4px and 12px
                    const size = Math.random() * 8 + 4;
                    particle.style.width = size + 'px';
                    particle.style.height = size + 'px';

                    // Random position
                    particle.style.left = Math.random() * 100 + '%';
                    particle.style.top = Math.random() * 100 + '%';

                    // Random animation duration
                    particle.style.animationDuration = (Math.random() * 10 + 5) + 's';
                    particle.style.animationDelay = Math.random() * 5 + 's';

                    particlesContainer.appendChild(particle);
                }
            }

            // Initialize particles
            createParticles();

            // Add staggered animation delay
            let animationDelay = 0;

            $.ajax({
                url: `/api/polls/user`,
                method: 'GET',
                success: function(response) {
                    // Hide loading spinner
                    $('#loadingSpinner').fadeOut(300);

                    const container = $('#pollListByUser');
                    container.empty();

                    if (response.length === 0) {
                        const emptyStateHtml = `
                    <div class="col-12">
                        <div class="empty-state">
                            <i class="fas fa-poll-h"></i>
                            <h3>No Polls Found</h3>
                            <p>There are currently no polls in this category.<br>Check back later for new content!</p>
                        </div>
                    </div>`;
                        container.html(emptyStateHtml);
                        return;
                    }

                    response.forEach((poll, index) => {
                        animationDelay += 100; // Stagger animations by 100ms

                        const html = `
                    <div class="col-md-6 col-lg-4 mb-4">
                        <div class="card modern-poll-card h-100" 
                             style="animation-delay: ${animationDelay}ms;"
                             onclick="window.location.href='/polls/view/${poll.public_id}'">
                            <div class="card-body">
                                <h5 class="poll-question">${poll.question}</h5>
                                <div class="poll-meta">
                                    <i class="fas fa-clock"></i>
                                    Created ${poll.created_diff}
                                </div>
                                <a href="/polls/view/${poll.public_id}"
                                   class="view-btn"
                                   onclick="event.stopPropagation();">
                                    View & Vote
                                    <i class="fas fa-arrow-right"></i>
                                </a>
                            </div>
                        </div>
                    </div>`;
                        container.append(html);
                    });
                },
                error: function() {
                    // Hide loading spinner
                    $('#loadingSpinner').fadeOut(300);

                    const errorStateHtml = `
                <div class="col-12">
                    <div class="alert error-state">
                        <i class="fas fa-exclamation-triangle"></i>
                        <h3>Oops! Something went wrong</h3>
                        <p>Failed to load polls. Please try refreshing the page.</p>
                        <button class="btn-glass btn-primary-glass mt-3" onclick="location.reload()">
                            <i class="fas fa-redo me-2"></i>Try Again
                        </button>
                    </div>
                </div>`;
                    $('#pollListByUser').html(errorStateHtml);
                }
            });
        });
    </script>
@endpush
